# Generated by Django 3.1 on 2020-09-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_info',
            fields=[
                ('id_cat', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('politique', models.BooleanField()),
                ('parties_politiques', models.BooleanField()),
                ('parlement', models.BooleanField()),
                ('Histoire', models.BooleanField()),
                ('economie', models.BooleanField()),
                ('tourisme', models.BooleanField()),
                ('bourse', models.BooleanField()),
                ('immobilier', models.BooleanField()),
                ('sport', models.BooleanField()),
                ('football', models.BooleanField()),
                ('société', models.BooleanField()),
                ('réseaux_sociaux', models.BooleanField()),
                ('santé', models.BooleanField()),
                ('covid', models.BooleanField()),
                ('science', models.BooleanField()),
                ('agriculture', models.BooleanField()),
                ('espace', models.BooleanField()),
                ('nature', models.BooleanField()),
                ('animaux', models.BooleanField()),
                ('religion', models.BooleanField()),
                ('eid_el_adha', models.BooleanField()),
                ('revue', models.BooleanField()),
                ('revue_presse', models.BooleanField()),
                ('revue_web', models.BooleanField()),
                ('rumeurs', models.BooleanField()),
                ('statistiques', models.BooleanField()),
                ('célébrité', models.BooleanField()),
                ('divertissement', models.BooleanField()),
                ('monde', models.BooleanField()),
                ('culture', models.BooleanField()),
                ('local_trends', models.BooleanField()),
                ('loi_décret', models.BooleanField()),
                ('terrorisme', models.BooleanField()),
                ('meteo', models.BooleanField()),
                ('blessures', models.BooleanField()),
                ('education', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='temporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('pos_neg', models.CharField(max_length=100)),
                ('simp_comp', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category_info')),
            ],
        ),
    ]
