# Generated by Django 3.1 on 2020-09-02 21:43

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_info',
            name='id_cat',
            field=models.CharField(blank=True, default='', max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
