# Generated by Django 3.1 on 2020-09-02 23:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200902_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_cat',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='category_info',
            name='id_cat',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
