# Generated by Django 3.1 on 2020-09-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200903_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_cat',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category_info',
            name='id_cat',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
