# Generated by Django 3.1 on 2020-09-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200903_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_info',
            old_name='id_cat',
            new_name='id_cat_info',
        ),
    ]
