# Generated by Django 3.1 on 2020-09-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200903_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
