# Generated by Django 3.1 on 2020-09-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200904_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='article',
            field=models.CharField(default='temp', max_length=10000),
            preserve_default=False,
        ),
    ]
