# Generated by Django 3.1.1 on 2020-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_info',
            name='article',
            field=models.CharField(default='temp', max_length=10000),
            preserve_default=False,
        ),
    ]
