# Generated by Django 3.1.1 on 2020-09-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_category_info_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='article',
        ),
    ]
